version: '3.9'
services:
  test_db:
    container_name: test_db
    image: postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD : test_pass
      POSTGRES_DB: TEST_DB
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5436:5432"